pom:
  version: @project.version@
token: ${TOKEN}
locale: ${LOCALE:#{""}}
motd: ${MOTD:#{""}}
defaultTrackList: ${DEFAULT_TRACK:#{""}}
cleaningImageUrl: ${CLEANING_IMAGE:#{""}}
debug: ${DEBUG:#{false}}
ytApiKey: ${YT_API_KEY:#{""}}